
create table blogs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title varchar(128) NOT NULL,
  content_HTML Text NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  primary key (id)
);